version: '3.1'

services:
    user-service:
        image: epamuladzislauvaliavaty/user-service
        ports:
            - "8081:8080"
        restart: on-failure
        environment:
            DB_DOMAIN: host.docker.internal
            DB_PORT: 5433
            DB_NAME: user-db
            DB_USERNAME: admin
            DB_PASSWORD: password
        depends_on:
            - user-service-postgres
    post-service:
        image: epamuladzislauvaliavaty/post-service
        ports:
            - "8082:8080"
        restart: on-failure
        environment:
            DB_DOMAIN: host.docker.internal
            DB_PORT: 5434
            DB_NAME: post-service-db
            DB_USERNAME: admin
            DB_PASSWORD: password
            USER_SERVICE_URL: http://host.docker.internal:8081
        depends_on:
            - post-service-postgres
    user-service-postgres:
        image: postgres:15.2
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: user-db
        ports:
            - "5433:5432"
    post-service-postgres:
        image: postgres:15.2
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: post-service-db
        ports:
            - "5434:5432"
            