apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
  namespace: k8s-program
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
