apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-cm
  namespace: {{ .Values.namespace }}
data:
  DB_DOMAIN: 10.100.187.198
  DB_PORT: "5432"
  DB_NAME: user-db

  init.sql: |
    CREATE TABLE users (
      id bigserial NOT NULL,
      amount_of_posts int4 NULL,
      username varchar(10) NULL,
      CONSTRAINT users_pkey PRIMARY KEY (id)
    );
    
    INSERT INTO users (username, amount_of_posts) VALUES('user-1', 1);
    INSERT INTO users (username, amount_of_posts) VALUES('user-2', 1);
    INSERT INTO users (username, amount_of_posts) VALUES('user-3', 3);
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-service-cm
  namespace: {{ .Values.namespace }}
data:
  DB_DOMAIN: 10.110.170.72
  DB_PORT: "5432"
  DB_NAME: post-service-db
  USER_SERVICE_URL: http://192.168.65.4:30008 # Worker Node InternalIP address + Node Port

  init.sql: |
    CREATE TABLE posts (
      id bigserial NOT NULL,
      author_id int8 NULL,
      posted_at timestamp(6) NULL,
      "text" varchar(50) NULL,
      "topic" varchar(50) NULL,
      CONSTRAINT posts_pkey PRIMARY KEY (id)
    );

    INSERT INTO posts (author_id, posted_at, "text") VALUES(1, '2023-04-28 12:34:25', 'example text 1');
    INSERT INTO posts (author_id, posted_at, "text") VALUES(2, '2023-04-28 12:35:25', 'example text 2');
    INSERT INTO posts (author_id, posted_at, "text") VALUES(3, '2023-04-28 12:36:25', 'example text 3');
    INSERT INTO posts (author_id, posted_at, "text") VALUES(3, '2023-04-28 12:37:25', 'example text 4');
    INSERT INTO posts (author_id, posted_at, "text") VALUES(3, '2023-04-28 12:38:25', 'example text 5');
---
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: {{ .Values.namespace }}
data:
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: post-db-secret
  namespace: {{ .Values.namespace }}
data:
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: cGFzc3dvcmQ=
