apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: user-service
  clusterIP: 10.110.170.71
  ports:
  - protocol: TCP
    port: 20008
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: post-service-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: post-service
  ports:
  - protocol: TCP
    port: 20009
    targetPort: 8080
