apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db-ss
  namespace: {{ .Values.namespace }}
spec:
  serviceName: user-db-service
  selector:
    matchLabels:
      app: user-db-pod
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: user-db-pod
    spec:
      volumes:
        - name: user-init-db-volume
          configMap:
            name: user-service-cm
            items:
              - key: "init.sql"
                path: "init.sql"
      containers:
        - name: user-db
          image: postgres:15.2
          ports:
            - containerPort: 5432
          startupProbe:
            exec:
              command: ["psql", "-U", "admin", "-d", "user-db", "-c", "SELECT 1"]
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-U", "admin", "-d", "user-db", "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command: ["psql", "-U", "admin", "-d", "user-db", "-c", "SELECT 1"]
            initialDelaySeconds: 3
            timeoutSeconds: 2
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGPASSWORD # this this is needed for probes to work
              value: password
            - name: POSTGRES_DB
              value: user-db
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - name: user-db-volume
              mountPath: /data
            - name: user-init-db-volume
              mountPath: "/docker-entrypoint-initdb.d"
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: user-db-volume
        namespace: {{ .Values.namespace }}
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: post-db-ss
  namespace: {{ .Values.namespace }}
spec:
  serviceName: post-db-service
  selector:
    matchLabels:
      app: post-db-pod
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: post-db-pod
    spec:
      volumes:
        - name: post-init-db-volume
          configMap:
            name: post-service-cm
            items:
              - key: "init.sql"
                path: "init.sql"
      containers:
        - name: post-db
          image: postgres:15.2
          ports:
            - containerPort: 5432
          startupProbe:
            exec:
              command: ["psql", "-U", "admin", "-d", "post-service-db", "-c", "SELECT 1"]
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-U", "admin", "-d", "post-service-db", "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command: ["psql", "-U", "admin", "-d", "post-service-db", "-c", "SELECT 1"]
            initialDelaySeconds: 3
            timeoutSeconds: 2
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGPASSWORD # this this is needed for probes to work
              value: password
            - name: POSTGRES_DB
              value: post-service-db
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - name: post-db-volume
              mountPath: /data
            - name: post-init-db-volume
              mountPath: "/docker-entrypoint-initdb.d"
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: post-db-volume
        namespace: {{ .Values.namespace }}
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
